/**
 * ESPN's English country name → Dutch, for national-team fixtures.
 *
 * Covers every UEFA member plus the nations the Netherlands is likely to meet at a
 * World Cup or in a friendly. ESPN's spelling has shifted over the years (Turkey →
 * Türkiye, Czech Republic → Czechia), so both forms are listed where that happened.
 * A country missing from this table simply keeps its English name.
 */
export const DUTCH_COUNTRY: Record<string, string> = {
  // UEFA
  Albania: 'Albanië',
  Andorra: 'Andorra',
  Armenia: 'Armenië',
  Austria: 'Oostenrijk',
  Azerbaijan: 'Azerbeidzjan',
  Belarus: 'Wit-Rusland',
  Belgium: 'België',
  'Bosnia and Herzegovina': 'Bosnië en Herzegovina',
  'Bosnia-Herzegovina': 'Bosnië en Herzegovina',
  Bulgaria: 'Bulgarije',
  Croatia: 'Kroatië',
  Cyprus: 'Cyprus',
  Czechia: 'Tsjechië',
  'Czech Republic': 'Tsjechië',
  Denmark: 'Denemarken',
  England: 'Engeland',
  Estonia: 'Estland',
  'Faroe Islands': 'Faeröer',
  Finland: 'Finland',
  France: 'Frankrijk',
  Georgia: 'Georgië',
  Germany: 'Duitsland',
  Gibraltar: 'Gibraltar',
  Greece: 'Griekenland',
  Hungary: 'Hongarije',
  Iceland: 'IJsland',
  Israel: 'Israël',
  Italy: 'Italië',
  Kazakhstan: 'Kazachstan',
  Kosovo: 'Kosovo',
  Latvia: 'Letland',
  Liechtenstein: 'Liechtenstein',
  Lithuania: 'Litouwen',
  Luxembourg: 'Luxemburg',
  Malta: 'Malta',
  Moldova: 'Moldavië',
  Montenegro: 'Montenegro',
  Netherlands: 'Nederland',
  'North Macedonia': 'Noord-Macedonië',
  'Northern Ireland': 'Noord-Ierland',
  Norway: 'Noorwegen',
  Poland: 'Polen',
  Portugal: 'Portugal',
  'Republic of Ireland': 'Ierland',
  Ireland: 'Ierland',
  Romania: 'Roemenië',
  Russia: 'Rusland',
  'San Marino': 'San Marino',
  Scotland: 'Schotland',
  Serbia: 'Servië',
  Slovakia: 'Slowakije',
  Slovenia: 'Slovenië',
  Spain: 'Spanje',
  Sweden: 'Zweden',
  Switzerland: 'Zwitserland',
  Türkiye: 'Turkije',
  Turkey: 'Turkije',
  Ukraine: 'Oekraïne',
  Wales: 'Wales',

  // Rest of the world
  Algeria: 'Algerije',
  Argentina: 'Argentinië',
  Australia: 'Australië',
  Bolivia: 'Bolivia',
  Brazil: 'Brazilië',
  Cameroon: 'Kameroen',
  Canada: 'Canada',
  'Cape Verde': 'Kaapverdië',
  Chile: 'Chili',
  China: 'China',
  Colombia: 'Colombia',
  'Costa Rica': 'Costa Rica',
  "Côte d'Ivoire": 'Ivoorkust',
  'Ivory Coast': 'Ivoorkust',
  Curaçao: 'Curaçao',
  Ecuador: 'Ecuador',
  Egypt: 'Egypte',
  Ghana: 'Ghana',
  Haiti: 'Haïti',
  Honduras: 'Honduras',
  Indonesia: 'Indonesië',
  Iran: 'Iran',
  Iraq: 'Irak',
  Jamaica: 'Jamaica',
  Japan: 'Japan',
  Jordan: 'Jordanië',
  Mexico: 'Mexico',
  Morocco: 'Marokko',
  'New Zealand': 'Nieuw-Zeeland',
  Nigeria: 'Nigeria',
  Panama: 'Panama',
  Paraguay: 'Paraguay',
  Peru: 'Peru',
  Qatar: 'Qatar',
  'Saudi Arabia': 'Saoedi-Arabië',
  Senegal: 'Senegal',
  'South Africa': 'Zuid-Afrika',
  'South Korea': 'Zuid-Korea',
  'Korea Republic': 'Zuid-Korea',
  Suriname: 'Suriname',
  Tunisia: 'Tunesië',
  'United States': 'Verenigde Staten',
  USA: 'Verenigde Staten',
  Uruguay: 'Uruguay',
  Uzbekistan: 'Oezbekistan',
  Venezuela: 'Venezuela',
}
